name: oche_script
version: 1.0.0+1
description: OcheScript embeddable script language for Flutter/Dart applications.
homepage: https://atebitftw.github.io/site/
repository: https://github.com/atebitftw/ochescript
issue_tracker: https://github.com/atebitftw/ochescript/issues
platforms:
  web:
  windows:
  linux:
  macos:
  android:
  ios:
topics:
  - script
  - language
  - embeddable
  - scripting
executables:
  oche:
dependencies:
  args: ^2.7.0
  logging: ^1.3.0
  meta: ^1.17.0
dev_dependencies:
  test: ^1.28.0
environment:
  sdk: ^3.10.3